apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mlflow
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    name: http
